### ISSUE TITLE
GOAT:Hack 4/3/19 Roadmap

### ISSUE THREAD

**Issue by mstenta** [julietnpn/plantdataservice#2]
We spent a long time talking about the goals we would like to aim towards with this project - but decided that for the GOAT:Hack event the priority would be to create a minimum-viable product (MVP) for a plant data service. This essentially just means we will define the *start* of a database schema, import some example data into it, provide a simple web UI to view it, and a simple REST API for getting plant lists.

- [x] Discuss requirements, challenges, etc.
- [x] Define a basic database schema in Python (with SQLAlchemy).
- [x] Create a basic web UI (with Flask Admin).
- [x] Create a basic REST API to get the plant list (with Flask RESTful).
- [x] Deploy to Cloud.gov (with the help of @pburkholder).
- [x] Import an example plant list from USDA cover crops spreadsheet.
- [x] Proof of concept farmOS module that pulls in crop list (https://github.com/mstenta/farm_plantservice).
- [x] Document and present to other GOAT:Hack groups.

**Comment by mstenta** [comment]
I created an issue we can use to discuss what we would like to see happen before version 1: https://github.com/julietnpn/plantdataservice/issues/7
